---
version: 2
before:
  hooks:
    - go mod download
builds:
  - id: npmi-go
    binary: npmi-go
    main: main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: linux
        goarch: arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - >-
        -s -w -X github.com/hermo/npmi-go/pkg/npmi.Version={{.Version}}
        -X github.com/hermo/npmi-go/pkg/npmi.Commit={{.Commit}}
        -X github.com/hermo/npmi-go/pkg/npmi.CommitDate={{ .CommitDate }}
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge pull request
      - Merge branch
      - go mod tidy
archives:
  - id: tgz
    formats: ['tar.gz']
    wrap_in_directory: false

report_sizes: true

signs:
  - id: minisign
    signature: "${artifact}.minisig"
    cmd: "sh"
    args:
      - "-c"
      - "minisign -s /dev/shm/npmi-go.sec -Sm ${artifact} < /dev/shm/npmi-go.pass"
    artifacts: all
  - id: gpg
    cmd: gpg
    args:
      - "-b"
      - "-u"
      - "6EC0B01FE03C53FA44E86D930A63E5AB0A045A2D"
      - "-o"
      - "${signature}"
      - "${artifact}"
    artifacts: all

nfpms:
  - vendor: Mirko Grönroos
    homepage: https://github.com/hermo/npmi-go
    maintainer: Mirko Grönroos <mirko@mirko.fi>
    description: npmi-go caches the contents of node_modules directory locally or in a Minio instance
    license: MIT
    formats:
      - deb
      - rpm
    dependencies: []

brews:
  - repository:
      owner: hermo
      name: homebrew-npmi
    download_strategy: CurlDownloadStrategy
    commit_author:
      name: goreleaserbot
      email: mirko+goreleaser@mirko.fi
    directory: Formula
    caveats: "Note that npmi-go is work-in-progress and should not be used in production."
    homepage: "https://github.com/hermo/npmi-go"
    description: "npmi-go caches the contents of node_modules directory in a tarball stored locally or in a Minio instance"
    license: "MIT"
    skip_upload: auto
