---
before:
  hooks:
    - go mod download
builds:
  - id: npmi-go
    binary: npmi-go
    main: main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: linux
        goarch: arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags: >-
      -s -w -X github.com/hermo/npmi-go/cmd.version={{.Version}}
      -X github.com/hermo/npmi-go/cmd.commit={{.Commit}}
      -X github.com/hermo/npmi-go/cmd.date={{ .CommitDate }}
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge pull request
      - Merge branch
      - go mod tidy
archives:
  - id: tgz
    format: tar.gz
    replacements:
      darwin: macOS
    format_overrides:
      - goos: windows
        format: zip

signs:
  - signature: "${artifact}.minisig"
    cmd: "sh"
    args:
      - "-c"
      - "minisign -s /mnt/st1/npmi-go.sec -Sm ${artifact} < /mnt/st1/npmi-go.pass"
    artifacts: all

nfpms:
  - vendor: Mirko Grönroos
    homepage: https://github.com/hermo/npmi-go
    maintainer: Mirko Grönroos <mirko@mirko.fi>
    description: npmi-go caches the contents of node_modules directory locally or in a Minio instance
    license: MIT
    formats:
      - deb
      - rpm
brews:
  -
    tap:
      owner: hermo
      name: homebrew-npmi

    download_strategy: CurlDownloadStrategy

    commit_author:
      name: goreleaserbot
      email: mirko+goreleaser@mirko.fi

    # The project name and current git tag are used in the format string.
    #commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

    folder: Formula
    caveats: "Note that npmi-go is work-in-progress and should not be used in production."
    homepage: "https://github.com/hermo/npmi-go"
    description: "npmi-go caches the contents of node_modules directory in a tarball stored locally or in a Minio instance"
    license: "MIT"

    # Setting this will prevent goreleaser to actually try to commit the updated
    # formula - instead, the formula file will be stored on the dist folder only,
    # leaving the responsibility of publishing it to the user.
    # If set to auto, the release will not be uploaded to the homebrew tap
    # in case there is an indicator for prerelease in the tag e.g. v0.0.0-rc1
    # Default is false.
    skip_upload: auto